### ISSUE TITLE
Colores en la tabla

### ISSUE THREAD

**Issue by curler007** [altapia/f1limb#10]
Los colores en la tabla deberían seguir este criterio dependiente de la posición y no de los puntos:
-1º --> Color oro
-2º --> Color plata
-3º --> Color bronce
-Algún punto --> Color verde 
-0 puntos --> Color blanco
-DNF --> Color negro

**Comment by altapia** [comment]
Completado a763adda8f3193f8ed26f4a3f6676bb8e6144b19
